[build]
publish = "."

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/cv"
to = "/Granth%20Jain%20CV.pdf"
status = 200

[[redirects]]
from = "/admin"
to = "/admin.html"
status = 200
